import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  components: [{ type: 'autogenerated', dirName: 'components' }],
};

export default sidebars;
