import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
	components: [{ type: 'autogenerated', dirName: 'components' }],
	guide: [{ type: 'autogenerated', dirName: 'guide' }],
}

export default sidebars
